language: r
sudo: false
dist: trusty
cache: package
r: 3.4.1
r_packages:
- covr
- devtools
- testthat
bioc_packages:
- GenomicRanges
- VariantAnnotation
- DNAcopy
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
script:
- "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- travis_wait Rscript -e 'covr::codecov()'
