language: r
sudo: false
cache: packages
r: 4.0.2
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-examples"
bioc_packages:
- S4Vectors
- rtracklayer
- GenomicRanges
- VariantAnnotation
before_install:
- curl -OL $URL
- mv jabba.tar.gz.gpg?dl=0 jabba.tar.gz.gpg
- echo $JAB | sudo gpg --passphrase-fd 0 jabba.tar.gz.gpg
- mkdir $HOME/my.cplex && tar -xvzf jabba.tar.gz --directory $HOME/my.cplex/
- curl -OL https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
script: "./travis-tool.sh run_tests"
nafter_failure:
- "./travis-tool.sh dump_logs"
after_success:
- travis_wait Rscript -e 'covr::codecov()'
env:
  global:
  - CPLEX_DIR=$HOME/my.cplex/
  - CPLEX_INCLUDE_PATH=$HOME/my.cplex/include
  - CPLEX_LIB_PATH=$HOME/my.cplex/lib
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --no-examples"
  - _R_CHECK_TESTS_NLINES_=0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
  - _R_CHECK_FORCE_SUGGESTS_=false
  - secure: RRusVQZ21CeJVt5wCREQ6fbHc6ETu7Zyh3dU0hiLPXp2yZj5m+9GwUE2jbNwIL7Vb9cMpvNU/6AvyaI2VPqDxsaz9cUnOPNZSbd+NZGIXYeExzgbA/u3oc/KsyY63RsTMrAYQS6P1cb9w/pjvkC+uLEKtEJ/Am7LdmffGE4UhBFmW+Bq65ULmcejb7N2PXDlsvllH37JVb4HP2+UbOA4Hxut3YUVuLSJ2eNOW1bpKqWcYNG5lKKZIYBR1+lD6c15HAj8j7+C0RxyFMk+qssM5ybt9oXTR77GNI2p2RYxLJOCUO8u5ukrxjZEgDbGdIyoPviG4PugD4gKpg6JxV5QJWhF2kCEZ4cXivh5QN5AZXZvTIl5WJahDVmfsdgIhduH000lOiTQccSQ8/rDuKbCz+pTgLvF7UQT5AqcaAPiOsV2FEUKP7KytFcz9yS47dIxaUbj2S6UUOxEZUwsstZVWDdmsWu7svn1i9KlF2qSZZj5BQw8babwGuDfK8DV7qgYV1ZcYedXH6l7LJ7LVXE3sTMUfWNkYENPb4JNu8RFGn8LXrivYrCaQiY7ZePMCoaQOR+RjoZEXVDTx2yPJ159oaXA6SbM77igMGAbCCf3YzXo/IKFFl87LRhjo1EVUOV3Hgx0ZHAH6TGIcgNQkdKfZp69n0ANO2Sx8y+TeJDBMBo=
  - secure: jE8ihPwV8EfA07qXHknpBizrrUm/p+T19VwLR2xudA4SRHnryS+WA6YUHu9wjWr6mzfUZn01sIl9R/pyUHCzZ2iEyjp1Nodc3cWFXqbxWvEltYBkVh+Mui/WZ2YWmLU5FlrKOCPPMSw8h/4jxAhtBTe7+SbIJ4vmsx8rhq4oLLJT1czcrLx3qMQO1M0BJeYf8XhetehiPKfUZMa+hBNszttTNwx/tNrPdogmQAO1zfNF5utZ+fEnKgJvTYgwvcNYiRhVUZ7dlN839hQ6HwWhz6qEwifMxTISh/oHBNXGYJgibcj1Qe+qrmTn7+1wakjKh+Crsctv8v/3nI3rzWCABrBSsC9zwRDPwNWT0qlzzJjhO0Yhhc8E1xpt84vdPv/Mh+mmpU4TC6CqHAY7hjpndvKhj3gOdX+Q2PbJOJGv2Rs+h5f1NGfYjQ2b1DvcHva0wfmPdipLEVNQJN+GvTfKCav8bU/GMyQEeGw7AamgVUZ6w24PaDMNc5CzYfTwN4YlH+L9Mv94cwwCxkVhFC2QIp1ubpOXhNGCKnbSSbArQvkyFL8TcquX4cV+ghmdsYzpF5Vye345uDarMOSAXZw4aodJRW5OWWtJrmr+n3RncEQbJaBv4mLbUSa7V2hxPqx7h0iew9N7MYPkadGqZdBsVu1N5zfNFe1A4bu1l7lFnsA=
